version: '3.4'

services:
    smartedu:
        image: ${DOCKER_REGISTRY-}smartedu
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - "redis"
        ports:
            - "32222:80"
            - "32222:443"
        links:
            - "redis"
    redis:
        image: redis
        ports:
            - "6379:6379"
